export const LoadsListTableData = [
  {
    Load: "Box 203",
    Status: "Cancelled",
    customer: "Jane Cooper",
    origin: "vulputate",
    LatestNote: "Note..",
    destination: "vulputate",
    Pickuptime: "20:00",
    pickup: "neque",
    dropofftime: "9:00",
    carrier: "ut",
    equip: "vulputate",
    commodity: "aliquet",
    mileage: "lorem",
    owner: "Admin",
    owner1: "Admin",
    owner2: "sodales",
  },
  {
    Load: "Haevy 203",
    Status: "Delivered",
    customer: "Arlene McCoy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "9:00",
    pickup: "fringilla",
    dropofftime: "21:00",
    carrier: "nunc",
    equip: "Admin",
    commodity: "Admin",
    mileage: "Admin",
    owner: "Admin",
    owner1: "Admin",
    owner2: "suspendisse",
  },
  {
    Load: "Some loads",
    Status: "Cancelled",
    customer: "Kathryn Murphy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "1:00",
    pickup: "mauris",
    dropofftime: "2:00",
    carrier: "ultricies",
    equip: "Admin",
    commodity: "Admin",
    mileage: "lorem",
    owner: "Admin",
    owner1: "Admin",
    owner2: "accumsan",
  },
  {
    Load: "Haevy 203",
    Status: "Delivered",
    customer: "Arlene McCoy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "9:00",
    pickup: "fringilla",
    dropofftime: "21:00",
    carrier: "nunc",
    equip: "Admin",
    commodity: "Admin",
    mileage: "Admin",
    owner: "Admin",
    owner1: "Admin",
    owner2: "suspendisse",
  },
  {
    Load: "Some loads",
    Status: "Delivered",
    customer: "Kathryn Murphy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "1:00",
    pickup: "mauris",
    dropofftime: "2:00",
    carrier: "ultricies",
    equip: "Admin",
    commodity: "Admin",
    mileage: "lorem",
    owner: "Admin",
    owner1: "Admin",
    owner2: "accumsan",
  },
  {
    Load: "Haevy 203",
    Status: "Delivered",
    customer: "Arlene McCoy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "9:00",
    pickup: "fringilla",
    dropofftime: "21:00",
    carrier: "nunc",
    equip: "Admin",
    commodity: "Admin",
    mileage: "Admin",
    owner: "Admin",
    owner1: "Admin",
    owner2: "suspendisse",
  },
  {
    Load: "Some loads",
    Status: "Cancelled",
    customer: "Kathryn Murphy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "1:00",
    pickup: "mauris",
    dropofftime: "2:00",
    carrier: "ultricies",
    equip: "Admin",
    commodity: "Admin",
    mileage: "lorem",
    owner: "Admin",
    owner1: "Admin",
    owner2: "accumsan",
  },
  {
    Load: "Haevy 203",
    Status: "Delivered",
    customer: "Arlene McCoy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "9:00",
    pickup: "fringilla",
    dropofftime: "21:00",
    carrier: "nunc",
    equip: "Admin",
    commodity: "Admin",
    mileage: "Admin",
    owner: "Admin",
    owner1: "Admin",
    owner2: "suspendisse",
  },
  {
    Load: "Some loads",
    Status: "Delivered",
    customer: "Kathryn Murphy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "1:00",
    pickup: "mauris",
    dropofftime: "2:00",
    carrier: "ultricies",
    equip: "Admin",
    commodity: "Admin",
    mileage: "lorem",
    owner: "Admin",
    owner1: "Admin",
    owner2: "accumsan",
  },
  {
    Load: "Haevy 203",
    Status: "Delivered",
    customer: "Arlene McCoy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "9:00",
    pickup: "fringilla",
    dropofftime: "21:00",
    carrier: "nunc",
    equip: "Admin",
    commodity: "Admin",
    mileage: "Admin",
    owner: "Admin",
    owner1: "Admin",
    owner2: "suspendisse",
  },
  {
    Load: "Some loads",
    Status: "Cancelled",
    customer: "Kathryn Murphy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "1:00",
    pickup: "mauris",
    dropofftime: "2:00",
    carrier: "ultricies",
    equip: "Admin",
    commodity: "Admin",
    mileage: "lorem",
    owner: "Admin",
    owner1: "Admin",
    owner2: "accumsan",
  },
  {
    Load: "Box 203",
    Status: "Cancelled",
    customer: "Jane Cooper",
    origin: "vulputate",
    LatestNote: "Note..",
    destination: "vulputate",
    Pickuptime: "20:00",
    pickup: "neque",
    dropofftime: "9:00",
    carrier: "ut",
    equip: "vulputate",
    commodity: "aliquet",
    mileage: "lorem",
    owner: "Admin",
    owner1: "Admin",
    owner2: "sodales",
  },
  {
    Load: "Haevy 203",
    Status: "Delivered",
    customer: "Arlene McCoy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "9:00",
    pickup: "fringilla",
    dropofftime: "21:00",
    carrier: "nunc",
    equip: "Admin",
    commodity: "Admin",
    mileage: "Admin",
    owner: "Admin",
    owner1: "Admin",
    owner2: "suspendisse",
  },
  {
    Load: "Some loads",
    Status: "Cancelled",
    customer: "Kathryn Murphy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "1:00",
    pickup: "mauris",
    dropofftime: "2:00",
    carrier: "ultricies",
    equip: "Admin",
    commodity: "Admin",
    mileage: "lorem",
    owner: "Admin",
    owner1: "Admin",
    owner2: "accumsan",
  },
  {
    Load: "Haevy 203",
    Status: "Delivered",
    customer: "Arlene McCoy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "9:00",
    pickup: "fringilla",
    dropofftime: "21:00",
    carrier: "nunc",
    equip: "Admin",
    commodity: "Admin",
    mileage: "Admin",
    owner: "Admin",
    owner1: "Admin",
    owner2: "suspendisse",
  },
  {
    Load: "Some loads",
    Status: "Cancelled",
    customer: "Kathryn Murphy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "1:00",
    pickup: "mauris",
    dropofftime: "2:00",
    carrier: "ultricies",
    equip: "Admin",
    commodity: "Admin",
    mileage: "lorem",
    owner: "Admin",
    owner1: "Admin",
    owner2: "accumsan",
  },
  {
    Load: "Haevy 203",
    Status: "Delivered",
    customer: "Arlene McCoy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "9:00",
    pickup: "fringilla",
    dropofftime: "21:00",
    carrier: "nunc",
    equip: "Admin",
    commodity: "Admin",
    mileage: "Admin",
    owner: "Admin",
    owner1: "Admin",
    owner2: "suspendisse",
  },
  {
    Load: "Some loads",
    Status: "Delivered",
    customer: "Kathryn Murphy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "1:00",
    pickup: "mauris",
    dropofftime: "2:00",
    carrier: "ultricies",
    equip: "Admin",
    commodity: "Admin",
    mileage: "lorem",
    owner: "Admin",
    owner1: "Admin",
    owner2: "accumsan",
  },
  {
    Load: "Haevy 203",
    Status: "Delivered",
    customer: "Arlene McCoy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "9:00",
    pickup: "fringilla",
    dropofftime: "21:00",
    carrier: "nunc",
    equip: "Admin",
    commodity: "Admin",
    mileage: "Admin",
    owner: "Admin",
    owner1: "Admin",
    owner2: "suspendisse",
  },
  {
    Load: "Some loads",
    Status: "Cancelled",
    customer: "Kathryn Murphy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "1:00",
    pickup: "mauris",
    dropofftime: "2:00",
    carrier: "ultricies",
    equip: "Admin",
    commodity: "Admin",
    mileage: "lorem",
    owner: "Admin",
    owner1: "Admin",
    owner2: "accumsan",
  },
  {
    Load: "Box 203",
    Status: "Cancelled",
    customer: "Jane Cooper",
    origin: "vulputate",
    LatestNote: "Note..",
    destination: "vulputate",
    Pickuptime: "20:00",
    pickup: "neque",
    dropofftime: "9:00",
    carrier: "ut",
    equip: "vulputate",
    commodity: "aliquet",
    mileage: "lorem",
    owner: "Admin",
    owner1: "Admin",
    owner2: "sodales",
  },
  {
    Load: "Haevy 203",
    Status: "Delivered",
    customer: "Arlene McCoy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "9:00",
    pickup: "fringilla",
    dropofftime: "21:00",
    carrier: "nunc",
    equip: "Admin",
    commodity: "Admin",
    mileage: "Admin",
    owner: "Admin",
    owner1: "Admin",
    owner2: "suspendisse",
  },
  {
    Load: "Some loads",
    Status: "Cancelled",
    customer: "Kathryn Murphy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "1:00",
    pickup: "mauris",
    dropofftime: "2:00",
    carrier: "ultricies",
    equip: "Admin",
    commodity: "Admin",
    mileage: "lorem",
    owner: "Admin",
    owner1: "Admin",
    owner2: "accumsan",
  },
  {
    Load: "Haevy 203",
    Status: "Delivered",
    customer: "Arlene McCoy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "9:00",
    pickup: "fringilla",
    dropofftime: "21:00",
    carrier: "nunc",
    equip: "Admin",
    commodity: "Admin",
    mileage: "Admin",
    owner: "Admin",
    owner1: "Admin",
    owner2: "suspendisse",
  },
  {
    Load: "Some loads",
    Status: "Delivered",
    customer: "Kathryn Murphy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "1:00",
    pickup: "mauris",
    dropofftime: "2:00",
    carrier: "ultricies",
    equip: "Admin",
    commodity: "Admin",
    mileage: "lorem",
    owner: "Admin",
    owner1: "Admin",
    owner2: "accumsan",
  },
  {
    Load: "Haevy 203",
    Status: "Delivered",
    customer: "Arlene McCoy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "9:00",
    pickup: "fringilla",
    dropofftime: "21:00",
    carrier: "nunc",
    equip: "Admin",
    commodity: "Admin",
    mileage: "Admin",
    owner: "Admin",
    owner1: "Admin",
    owner2: "suspendisse",
  },
  {
    Load: "Some loads",
    Status: "Cancelled",
    customer: "Kathryn Murphy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "1:00",
    pickup: "mauris",
    dropofftime: "2:00",
    carrier: "ultricies",
    equip: "Admin",
    commodity: "Admin",
    mileage: "lorem",
    owner: "Admin",
    owner1: "Admin",
    owner2: "accumsan",
  },
  {
    Load: "Haevy 203",
    Status: "Delivered",
    customer: "Arlene McCoy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "9:00",
    pickup: "fringilla",
    dropofftime: "21:00",
    carrier: "nunc",
    equip: "Admin",
    commodity: "Admin",
    mileage: "Admin",
    owner: "Admin",
    owner1: "Admin",
    owner2: "suspendisse",
  },
  {
    Load: "Some loads",
    Status: "Delivered",
    customer: "Kathryn Murphy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "1:00",
    pickup: "mauris",
    dropofftime: "2:00",
    carrier: "ultricies",
    equip: "Admin",
    commodity: "Admin",
    mileage: "lorem",
    owner: "Admin",
    owner1: "Admin",
    owner2: "accumsan",
  },
  {
    Load: "Haevy 203",
    Status: "Delivered",
    customer: "Arlene McCoy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "9:00",
    pickup: "fringilla",
    dropofftime: "21:00",
    carrier: "nunc",
    equip: "Admin",
    commodity: "Admin",
    mileage: "Admin",
    owner: "Admin",
    owner1: "Admin",
    owner2: "suspendisse",
  },
  {
    Load: "Some loads",
    Status: "Cancelled",
    customer: "Kathryn Murphy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "1:00",
    pickup: "mauris",
    dropofftime: "2:00",
    carrier: "ultricies",
    equip: "Admin",
    commodity: "Admin",
    mileage: "lorem",
    owner: "Admin",
    owner1: "Admin",
    owner2: "accumsan",
  },
  {
    Load: "Box 203",
    Status: "Cancelled",
    customer: "Jane Cooper",
    origin: "vulputate",
    LatestNote: "Note..",
    destination: "vulputate",
    Pickuptime: "20:00",
    pickup: "neque",
    dropofftime: "9:00",
    carrier: "ut",
    equip: "vulputate",
    commodity: "aliquet",
    mileage: "lorem",
    owner: "Admin",
    owner1: "Admin",
    owner2: "sodales",
  },
  {
    Load: "Haevy 203",
    Status: "Delivered",
    customer: "Arlene McCoy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "9:00",
    pickup: "fringilla",
    dropofftime: "21:00",
    carrier: "nunc",
    equip: "Admin",
    commodity: "Admin",
    mileage: "Admin",
    owner: "Admin",
    owner1: "Admin",
    owner2: "suspendisse",
  },
  {
    Load: "Some loads",
    Status: "Cancelled",
    customer: "Kathryn Murphy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "1:00",
    pickup: "mauris",
    dropofftime: "2:00",
    carrier: "ultricies",
    equip: "Admin",
    commodity: "Admin",
    mileage: "lorem",
    owner: "Admin",
    owner1: "Admin",
    owner2: "accumsan",
  },
  {
    Load: "Haevy 203",
    Status: "Delivered",
    customer: "Arlene McCoy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "9:00",
    pickup: "fringilla",
    dropofftime: "21:00",
    carrier: "nunc",
    equip: "Admin",
    commodity: "Admin",
    mileage: "Admin",
    owner: "Admin",
    owner1: "Admin",
    owner2: "suspendisse",
  },
  {
    Load: "Some loads",
    Status: "Cancelled",
    customer: "Kathryn Murphy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "1:00",
    pickup: "mauris",
    dropofftime: "2:00",
    carrier: "ultricies",
    equip: "Admin",
    commodity: "Admin",
    mileage: "lorem",
    owner: "Admin",
    owner1: "Admin",
    owner2: "accumsan",
  },
  {
    Load: "Haevy 203",
    Status: "Delivered",
    customer: "Arlene McCoy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "9:00",
    pickup: "fringilla",
    dropofftime: "21:00",
    carrier: "nunc",
    equip: "Admin",
    commodity: "Admin",
    mileage: "Admin",
    owner: "Admin",
    owner1: "Admin",
    owner2: "suspendisse",
  },
  {
    Load: "Some loads",
    Status: "Delivered",
    customer: "Kathryn Murphy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "1:00",
    pickup: "mauris",
    dropofftime: "2:00",
    carrier: "ultricies",
    equip: "Admin",
    commodity: "Admin",
    mileage: "lorem",
    owner: "Admin",
    owner1: "Admin",
    owner2: "accumsan",
  },
  {
    Load: "Haevy 203",
    Status: "Delivered",
    customer: "Arlene McCoy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "9:00",
    pickup: "fringilla",
    dropofftime: "21:00",
    carrier: "nunc",
    equip: "Admin",
    commodity: "Admin",
    mileage: "Admin",
    owner: "Admin",
    owner1: "Admin",
    owner2: "suspendisse",
  },
  {
    Load: "Some loads",
    Status: "Cancelled",
    customer: "Kathryn Murphy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "1:00",
    pickup: "mauris",
    dropofftime: "2:00",
    carrier: "ultricies",
    equip: "Admin",
    commodity: "Admin",
    mileage: "lorem",
    owner: "Admin",
    owner1: "Admin",
    owner2: "accumsan",
  },
  {
    Load: "Box 203",
    Status: "Cancelled",
    customer: "Jane Cooper",
    origin: "vulputate",
    LatestNote: "Note..",
    destination: "vulputate",
    Pickuptime: "20:00",
    pickup: "neque",
    dropofftime: "9:00",
    carrier: "ut",
    equip: "vulputate",
    commodity: "aliquet",
    mileage: "lorem",
    owner: "Admin",
    owner1: "Admin",
    owner2: "sodales",
  },
  {
    Load: "Haevy 203",
    Status: "Delivered",
    customer: "Arlene McCoy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "9:00",
    pickup: "fringilla",
    dropofftime: "21:00",
    carrier: "nunc",
    equip: "Admin",
    commodity: "Admin",
    mileage: "Admin",
    owner: "Admin",
    owner1: "Admin",
    owner2: "suspendisse",
  },
  {
    Load: "Some loads",
    Status: "Cancelled",
    customer: "Kathryn Murphy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "1:00",
    pickup: "mauris",
    dropofftime: "2:00",
    carrier: "ultricies",
    equip: "Admin",
    commodity: "Admin",
    mileage: "lorem",
    owner: "Admin",
    owner1: "Admin",
    owner2: "accumsan",
  },
  {
    Load: "Haevy 203",
    Status: "Delivered",
    customer: "Arlene McCoy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "9:00",
    pickup: "fringilla",
    dropofftime: "21:00",
    carrier: "nunc",
    equip: "Admin",
    commodity: "Admin",
    mileage: "Admin",
    owner: "Admin",
    owner1: "Admin",
    owner2: "suspendisse",
  },
  {
    Load: "Some loads",
    Status: "Delivered",
    customer: "Kathryn Murphy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "1:00",
    pickup: "mauris",
    dropofftime: "2:00",
    carrier: "ultricies",
    equip: "Admin",
    commodity: "Admin",
    mileage: "lorem",
    owner: "Admin",
    owner1: "Admin",
    owner2: "accumsan",
  },
  {
    Load: "Haevy 203",
    Status: "Delivered",
    customer: "Arlene McCoy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "9:00",
    pickup: "fringilla",
    dropofftime: "21:00",
    carrier: "nunc",
    equip: "Admin",
    commodity: "Admin",
    mileage: "Admin",
    owner: "Admin",
    owner1: "Admin",
    owner2: "suspendisse",
  },
  {
    Load: "Some loads",
    Status: "Cancelled",
    customer: "Kathryn Murphy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "1:00",
    pickup: "mauris",
    dropofftime: "2:00",
    carrier: "ultricies",
    equip: "Admin",
    commodity: "Admin",
    mileage: "lorem",
    owner: "Admin",
    owner1: "Admin",
    owner2: "accumsan",
  },
  {
    Load: "Haevy 203",
    Status: "Delivered",
    customer: "Arlene McCoy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "9:00",
    pickup: "fringilla",
    dropofftime: "21:00",
    carrier: "nunc",
    equip: "Admin",
    commodity: "Admin",
    mileage: "Admin",
    owner: "Admin",
    owner1: "Admin",
    owner2: "suspendisse",
  },
  {
    Load: "Box 203",
    Status: "Cancelled",
    customer: "Jane Cooper",
    origin: "vulputate",
    LatestNote: "Note..",
    destination: "vulputate",
    Pickuptime: "20:00",
    pickup: "neque",
    dropofftime: "9:00",
    carrier: "ut",
    equip: "vulputate",
    commodity: "aliquet",
    mileage: "lorem",
    owner: "Admin",
    owner1: "Admin",
    owner2: "sodales",
  },
  {
    Load: "Haevy 203",
    Status: "Delivered",
    customer: "Arlene McCoy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "9:00",
    pickup: "fringilla",
    dropofftime: "21:00",
    carrier: "nunc",
    equip: "Admin",
    commodity: "Admin",
    mileage: "Admin",
    owner: "Admin",
    owner1: "Admin",
    owner2: "suspendisse",
  },
  {
    Load: "Some loads",
    Status: "Cancelled",
    customer: "Kathryn Murphy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "1:00",
    pickup: "mauris",
    dropofftime: "2:00",
    carrier: "ultricies",
    equip: "Admin",
    commodity: "Admin",
    mileage: "lorem",
    owner: "Admin",
    owner1: "Admin",
    owner2: "accumsan",
  },
  {
    Load: "Haevy 203",
    Status: "Delivered",
    customer: "Arlene McCoy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "9:00",
    pickup: "fringilla",
    dropofftime: "21:00",
    carrier: "nunc",
    equip: "Admin",
    commodity: "Admin",
    mileage: "Admin",
    owner: "Admin",
    owner1: "Admin",
    owner2: "suspendisse",
  },
  {
    Load: "Some loads",
    Status: "Delivered",
    customer: "Kathryn Murphy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "1:00",
    pickup: "mauris",
    dropofftime: "2:00",
    carrier: "ultricies",
    equip: "Admin",
    commodity: "Admin",
    mileage: "lorem",
    owner: "Admin",
    owner1: "Admin",
    owner2: "accumsan",
  },
  {
    Load: "Haevy 203",
    Status: "Delivered",
    customer: "Arlene McCoy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "9:00",
    pickup: "fringilla",
    dropofftime: "21:00",
    carrier: "nunc",
    equip: "Admin",
    commodity: "Admin",
    mileage: "Admin",
    owner: "Admin",
    owner1: "Admin",
    owner2: "suspendisse",
  },
  {
    Load: "Some loads",
    Status: "Cancelled",
    customer: "Kathryn Murphy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "1:00",
    pickup: "mauris",
    dropofftime: "2:00",
    carrier: "ultricies",
    equip: "Admin",
    commodity: "Admin",
    mileage: "lorem",
    owner: "Admin",
    owner1: "Admin",
    owner2: "accumsan",
  },
  {
    Load: "Haevy 203",
    Status: "Delivered",
    customer: "Arlene McCoy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "9:00",
    pickup: "fringilla",
    dropofftime: "21:00",
    carrier: "nunc",
    equip: "Admin",
    commodity: "Admin",
    mileage: "Admin",
    owner: "Admin",
    owner1: "Admin",
    owner2: "suspendisse",
  },
  {
    Load: "Some loads",
    Status: "Delivered",
    customer: "Kathryn Murphy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "1:00",
    pickup: "mauris",
    dropofftime: "2:00",
    carrier: "ultricies",
    equip: "Admin",
    commodity: "Admin",
    mileage: "lorem",
    owner: "Admin",
    owner1: "Admin",
    owner2: "accumsan",
  },
  {
    Load: "Haevy 203",
    Status: "Delivered",
    customer: "Arlene McCoy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "9:00",
    pickup: "fringilla",
    dropofftime: "21:00",
    carrier: "nunc",
    equip: "Admin",
    commodity: "Admin",
    mileage: "Admin",
    owner: "Admin",
    owner1: "Admin",
    owner2: "suspendisse",
  },
  {
    Load: "Some loads",
    Status: "Cancelled",
    customer: "Kathryn Murphy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "1:00",
    pickup: "mauris",
    dropofftime: "2:00",
    carrier: "ultricies",
    equip: "Admin",
    commodity: "Admin",
    mileage: "lorem",
    owner: "Admin",
    owner1: "Admin",
    owner2: "accumsan",
  },
  {
    Load: "Box 203",
    Status: "Cancelled",
    customer: "Jane Cooper",
    origin: "vulputate",
    LatestNote: "Note..",
    destination: "vulputate",
    Pickuptime: "20:00",
    pickup: "neque",
    dropofftime: "9:00",
    carrier: "ut",
    equip: "vulputate",
    commodity: "aliquet",
    mileage: "lorem",
    owner: "Admin",
    owner1: "Admin",
    owner2: "sodales",
  },
  {
    Load: "Haevy 203",
    Status: "Delivered",
    customer: "Arlene McCoy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "9:00",
    pickup: "fringilla",
    dropofftime: "21:00",
    carrier: "nunc",
    equip: "Admin",
    commodity: "Admin",
    mileage: "Admin",
    owner: "Admin",
    owner1: "Admin",
    owner2: "suspendisse",
  },
  {
    Load: "Some loads",
    Status: "Cancelled",
    customer: "Kathryn Murphy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "1:00",
    pickup: "mauris",
    dropofftime: "2:00",
    carrier: "ultricies",
    equip: "Admin",
    commodity: "Admin",
    mileage: "lorem",
    owner: "Admin",
    owner1: "Admin",
    owner2: "accumsan",
  },
  {
    Load: "Haevy 203",
    Status: "Delivered",
    customer: "Arlene McCoy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "9:00",
    pickup: "fringilla",
    dropofftime: "21:00",
    carrier: "nunc",
    equip: "Admin",
    commodity: "Admin",
    mileage: "Admin",
    owner: "Admin",
    owner1: "Admin",
    owner2: "suspendisse",
  },
  {
    Load: "Some loads",
    Status: "Cancelled",
    customer: "Kathryn Murphy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "1:00",
    pickup: "mauris",
    dropofftime: "2:00",
    carrier: "ultricies",
    equip: "Admin",
    commodity: "Admin",
    mileage: "lorem",
    owner: "Admin",
    owner1: "Admin",
    owner2: "accumsan",
  },
  {
    Load: "Haevy 203",
    Status: "Delivered",
    customer: "Arlene McCoy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "9:00",
    pickup: "fringilla",
    dropofftime: "21:00",
    carrier: "nunc",
    equip: "Admin",
    commodity: "Admin",
    mileage: "Admin",
    owner: "Admin",
    owner1: "Admin",
    owner2: "suspendisse",
  },
  {
    Load: "Some loads",
    Status: "Delivered",
    customer: "Kathryn Murphy",
    origin: "Admin",
    LatestNote: "Note..",
    destination: "Admin",
    Pickuptime: "1:00",
    pickup: "mauris",
    dropofftime: "2:00",
    carrier: "ultricies",
    equip: "Admin",
    commodity: "Admin",
    mileage: "lorem",
    owner: "Admin",
    owner1: "Admin",
    owner2: "accumsan",
  },
];

export const loadsActivity = [
  {
    loadsText: "Loads Available",
    ratio: "512",
    percentage: "+2.5%",
    comparedTo: 340,
  },
  {
    loadsText: "Loads Covered",
    ratio: "25",
    percentage: "-1.5%",
    comparedTo: 28,
  },
  {
    loadsText: "Loads in Transit",
    ratio: "125",
    percentage: "+0.5%",
    comparedTo: 120,
  },
  {
    loadsText: "Loads Earning",
    ratio: "$12632",
    percentage: "+2.5%",
    comparedTo: 10500,
  },
  {
    loadsText: "Carrier Number",
    ratio: "12",
    percentage: "+2.5%",
    comparedTo: 11,
  },
];

export const dataRaw = [
  200, 100, 200, 400, 360, 400, 600, 580, 520, 640, 1500, 500,
];
